// <auto-generated />
namespace cho500.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifyICD_10_CM_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyICD_10_CM_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "201702100621093_modifyICD_10_CM_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
